on:
  push:
    branches:
      - master
    # TODO: specify after stabilize repository 
    # paths:
    #   - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
        if: runner.os != 'Windows'
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 1.2.6
      - name: Build
        run: nimble build -Y
